

msg_template = "{download} {url} → {output}"
template = "{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] {pos:>7}/{len:7} ({percent}%) {msg}"
bar_chars = "█▌░"

workers = 4
buffer_size = 262144
pool_size = 100
retries = 3
min_parallel_size = 5242880
