name: Release
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
  release: 
env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: dwrs

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-14,ubuntu-latest,windows-latest]
        include:
          - os: macos-14
            target: aarch64-apple-darwin
            binary_suffix: -macos-arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_suffix: -linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_suffix: -windows-x86_64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare Binary
        shell: bash
        run: |
          mkdir -p release-assets

          if [ "${{ runner.os }}" == "Windows" ]; then
            cp target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}.exe \
            release-assets/${{ env.BINARY_NAME }}${{ matrix.binary_suffix }}
          else
            cp target/${{ matrix.target }}/release/${{ env.BINARY_NAME }} \
            release-assets/${{ env.BINARY_NAME }}${{ matrix.binary_suffix }}
            chmod +x release-assets/${{ env.BINARY_NAME }}${{ matrix.binary_suffix }}
          fi
          
      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: release-assets/${{ env.BINARY_NAME }}${{ matrix.binary_suffix }}
          retention-days: 1
  release:
    name: Create Github Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      conents: write

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binary-*
          merge-multiple: true
          path: ./dist

      - name: List files
        run: ls -lh ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          generate_release_notes: true
          draft: false
